FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-cache-dir ".[frontend]"
COPY frontend ./frontend
COPY .streamlit ./.streamlit
COPY outputs/customer_segments.csv ./outputs/customer_segments.csv
CMD ["streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
